#!/usr/bin/env php
<?php

declare(strict_types=1);

if (PHP_SAPI !== 'cli') {
    fwrite(STDERR, 'The cli script must be run from the command line.' . PHP_EOL);
    exit(1);
}

$app = require __DIR__ . '/bootstrap.php';

exit($app->get(\Core\Console\Kernel::class)->run($argv ?? $_SERVER['argv']));
