<?php

declare(strict_types=1);

namespace Core\Console\Commands;

use Core\Console\Command;
use Core\Http\Router;
use Core\Http\Route;

final class DocsApiCommand extends Command
{
    protected string $name = 'docs:api';

    protected string $description = 'Auto-generate docs/API-Endpoints.md from registered API routes.';

    public function handle(array $args, array $options): int
    {
        $router = $this->app->get(Router::class);
        $routes = array_values(array_filter(
            $router->getRoutes(),
            static fn (Route $route): bool => str_starts_with($route->uri, '/api'),
        ));

        $md = [];
        $md[] = '# API Reference';
        $md[] = '';
        $md[] = '> Auto-generated by `php cli docs:api`. Do not edit manually.';
        $md[] = '';
        $md[] = 'All responses follow the platform envelope:';
        $md[] = '';
        $md[] = '```json';
        $md[] = '{ "success": true, "message": "", "data": {} }';
        $md[] = '{ "success": false, "message": "", "errors": {} }';
        $md[] = '```';
        $md[] = '';
        $md[] = '| # | Method | Endpoint | Summary |';
        $md[] = '| --- | --- | --- | --- |';

        foreach (array_values($routes) as $i => $route) {
            $summary = $route->meta['doc']['summary'] ?? ($route->name ?? '');
            $md[] = sprintf('| %d | `%s` | `%s` | %s |', $i + 1, implode('/', $route->methods), $route->uri, $summary);
        }

        $md[] = '';
        $md[] = '## Endpoints';

        foreach ($routes as $route) {
            $doc = $route->meta['doc'] ?? [];
            $md[] = '';
            $md[] = '### `' . implode(' / ', $route->methods) . ' ' . $route->uri . '`';
            $md[] = '';
            if (($doc['summary'] ?? '') !== '') {
                $md[] = $doc['summary'];
                $md[] = '';
            }
            if (($doc['validation'] ?? []) !== []) {
                $md[] = '**Validation rules**';
                $md[] = '';
                $md[] = '| Field | Rules |';
                $md[] = '| --- | --- |';
                foreach ($doc['validation'] as $field => $rules) {
                    $md[] = '| `' . $field . '` | `' . $rules . '` |';
                }
                $md[] = '';
            }
            if (($doc['response'] ?? []) !== []) {
                $md[] = '**Example response**';
                $md[] = '';
                $md[] = '```json';
                $md[] = json_encode($doc['response'], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
                $md[] = '```';
                $md[] = '';
            }
            $md[] = '**Error codes:** `401` unauthenticated · `403` forbidden · `422` validation_failed · `404` not_found';
        }

        $target = $this->app->basePath('docs/API-Endpoints.md');
        @mkdir(dirname($target), 0775, true);
        file_put_contents($target, implode("\n", $md) . "\n");

        $this->success('Documented ' . count($routes) . ' API endpoints in docs/API-Endpoints.md');

        return 0;
    }
}
