<?php

declare(strict_types=1);

namespace Core\Console\Commands;

use Core\Console\Command;
use Core\Console\SchemaDiscovery;

final class ErdCommand extends Command
{
    protected string $name = 'erd';

    protected string $description = 'Generate a Mermaid ER diagram from database/schema definitions into database/erd/erd.md.';

    public function handle(array $args, array $options): int
    {
        $definitions = SchemaDiscovery::definitions($this->app->basePath('database/schema'));

        $lines = ['erDiagram'];
        $relations = [];

        foreach ($definitions as $definition) {
            $lines[] = '    ' . $definition->tableName() . ' {';
            foreach ($definition->blueprint()->columns() as $column) {
                $type = str_replace(['(', ')', ',', ' '], '_', $column->type);
                $lines[] = sprintf('        %s %s', $type, $column->name);
            }
            $lines[] = '    }';

            foreach ($definition->blueprint()->foreignKeys() as $foreign) {
                if ($foreign->referencedTable() !== '') {
                    $relations[] = sprintf(
                        '    %s ||--o{ %s : "%s"',
                        $foreign->referencedTable(),
                        $definition->tableName(),
                        $foreign->column,
                    );
                }
            }
        }

        $lines = array_merge($lines, array_values(array_unique($relations)));

        $out = $this->app->basePath('database/erd/erd.md');
        @mkdir(dirname($out), 0775, true);
        file_put_contents(
            $out,
            "# Entity Relationship Diagram\n\n> Generated by `php cli erd` from database/schema.\n\n```mermaid\n"
            . implode("\n", $lines)
            . "\n```\n",
        );

        $this->success('Wrote database/erd/erd.md (' . count($definitions) . ' entities)');

        return 0;
    }
}
