<?php

declare(strict_types=1);

namespace Core\Console\Commands;

use Core\Console\Command;
use Core\Console\SchemaDiscovery;
use Core\Database\DatabaseManager;

final class SchemaDumpCommand extends Command
{
    protected string $name = 'schema:dump';

    protected string $description = 'Write the full DDL generated from database/schema definitions to database/schema/schema.sql.';

    public function handle(array $args, array $options): int
    {
        $driver = $this->app->get(DatabaseManager::class)->connection()->driver();
        $definitions = SchemaDiscovery::definitions($this->app->basePath('database/schema'));

        $sql = ["-- Generated by `php cli schema:dump` (driver: {$driver})", ''];
        foreach ($definitions as $definition) {
            $sql[] = '-- table: ' . $definition->tableName();
            foreach ($definition->blueprint()->toStatements($driver) as $statement) {
                $sql[] = $statement . ';';
            }
            $sql[] = '';
        }

        $target = $this->app->basePath('database/schema/schema.sql');
        file_put_contents($target, implode(PHP_EOL, $sql));

        $this->success('Wrote ' . count($definitions) . ' table definitions to database/schema/schema.sql');

        return 0;
    }
}
